//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajuUminho.webforms {
    
    
    public partial class InterfaceEntidades {
        
        /// <summary>
        /// Form control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form;
        
        /// <summary>
        /// headerID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.utilizadores.i14TerminoDeSessao headerID;
        
        /// <summary>
        /// I83Insolventes1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i42Insolventes I83Insolventes1;
        
        /// <summary>
        /// I22RepresentanteLegal1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i22RepresentanteLegal I22RepresentanteLegal1;
        
        /// <summary>
        /// I22RepresentanteLegal2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i22RepresentanteLegal I22RepresentanteLegal2;
        
        /// <summary>
        /// I22RepresentanteLegal3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i22RepresentanteLegal I22RepresentanteLegal3;
        
        /// <summary>
        /// I26AdministradoresJudiciais1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i26AdministradoresJudiciais I26AdministradoresJudiciais1;
        
        /// <summary>
        /// I26AdministradoresJudiciais2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i26AdministradoresJudiciais I26AdministradoresJudiciais2;
        
        /// <summary>
        /// I26AdministradoresJudiciais3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i26AdministradoresJudiciais I26AdministradoresJudiciais3;
        
        /// <summary>
        /// I30Tribunais1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i30Tribunais I30Tribunais1;
        
        /// <summary>
        /// I30Tribunais2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i30Tribunais I30Tribunais2;
        
        /// <summary>
        /// I30Tribunais3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i30Tribunais I30Tribunais3;
        
        /// <summary>
        /// I34Juizes1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i34Juizes I34Juizes1;
        
        /// <summary>
        /// I34Juizes2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i34Juizes I34Juizes2;
        
        /// <summary>
        /// I34Juizes3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i34Juizes I34Juizes3;
        
        /// <summary>
        /// I38Credores1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i38Credores I38Credores1;
        
        /// <summary>
        /// I38Credores2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i38Credores I38Credores2;
        
        /// <summary>
        /// I38Credores3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i38Credores I38Credores3;
        
        /// <summary>
        /// i42Insolventes1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i42Insolventes i42Insolventes1;
        
        /// <summary>
        /// i42Insolventes2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i42Insolventes i42Insolventes2;
        
        /// <summary>
        /// i42Insolventes3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i42Insolventes i42Insolventes3;
        
        /// <summary>
        /// I46Contabilistas1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i46Contabilistas I46Contabilistas1;
        
        /// <summary>
        /// I46Contabilistas2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i46Contabilistas I46Contabilistas2;
        
        /// <summary>
        /// I46Contabilistas3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i46Contabilistas I46Contabilistas3;
        
        /// <summary>
        /// I50PrestadoresServico1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i50PrestadoresServico I50PrestadoresServico1;
        
        /// <summary>
        /// I50PrestadoresServico2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i50PrestadoresServico I50PrestadoresServico2;
        
        /// <summary>
        /// I50PrestadoresServico3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i50PrestadoresServico I50PrestadoresServico3;
        
        /// <summary>
        /// I54OutrasEntidade1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i54OutrasEntidades I54OutrasEntidade1;
        
        /// <summary>
        /// I54OutrasEntidades2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i54OutrasEntidades I54OutrasEntidades2;
        
        /// <summary>
        /// I54OutrasEntidades3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ajuUminho.controls.entidades.i54OutrasEntidades I54OutrasEntidades3;
    }
}
